### ISSUE TITLE
step by step guide?

### ISSUE THREAD

**Issue by koo9** [mrochon/b2csamples#1]
Thanks for the sample, it's exactly what I am looking for. just wondering if there is more pointers/documentation explaining how to configure this b2c multitenant app. thx!

**Comment by mrochon** [comment]
What level of detail are you looking for? In general, you will need to [setup the REST functions](https://docs.microsoft.com/en-us/azure/active-directory-b2c/custom-policy-rest-api-claims-exchange) first, then make sure your [B2C tenant is setup](https://docs.microsoft.com/en-us/azure/active-directory-b2c/custom-policy-get-started) for using IEF, then upload the Policy xml files and finally test and deploy the web application. Let me know if there is something particular that is causing you a problem and I will try to help.

**Comment by koo9** [comment]
I think in need steps on how to setup B2C applications and policies.

**Comment by mrochon** [comment]
Plenty of [docs ](https://docs.microsoft.com/en-us/azure/active-directory-b2c/)on the web. I suggested some specific pages from that above.

**Comment by koo9** [comment]
https://docs.microsoft.com/en-us/azure/active-directory-b2c/identity-provider-azure-ad-multi-tenant-custom?tabs=applications

went through this to set up multitenant custom policy, but got an error : AADB2C90289: We encountered an error connecting to the identity provider site:stackoverflow.com

any quick thoughts on what might gone wrong?

**Comment by lehne** [comment]
I was trying to set this up and was wondering how to set up the application and the REST application in Azure AD B2C? I'm not sure which client Ids to use for which.

**Comment by koo9** [comment]
https://github.com/Azure-Samples/active-directory-b2c-dotnet-webapp-and-webapi

please look at this example

**Comment by mrochon** [comment]
REST functions have two app registrations, both in the B2C tenant. First one ("B2C" element in appsettings) is needed so it can receive and validate user tokens from the Web Application. The 2nd ("ClientCreds") is needed so it can get tokens from AAD to call MS Graph (my deployment is using a self-signed X509 cert for the OAuth2 Client Credentials grant but you can use a symmetric key as well - it is simpler). Note that the 2nd registration needs to be done using the AAD Blade, not the regular B2C blade. The web application is registered (using the B2C blade) in the B2C tenant so it can authenticate users and get tokens to call the REST API on their behalf (the "AzureAD" section). The web also needs a secret to redeem the auth code for an access token and a separate secret to sign new user invitations. The latter needs to be stored in B2C (it is referenced in the IEF policies as InvitationTokenSigningKey). You create it yourself (os some secrets generator).

**Comment by lehne** [comment]
Ok I've gotten that mostly done--I went with a certificate as well since it seemed mostly set up for that. I'm now not sure about IdPSelect.html. Where is that supposed to be hosted?

**Comment by mrochon** [comment]
anywhere where it is publicly available. For example in Azure Blob storage: https://docs.microsoft.com/en-us/azure/active-directory-b2c/customize-ui-overview#where-do-i-store-ui-content

**Comment by mrochon** [comment]
I am not even sure anymore whether you need it. Just remove the ContentDefinition referencing it and try it & use the default layout.

**Comment by lehne** [comment]
I will try that next. I had forgotten to update a tenantId in the API project so I think I had multiple problems going on.

**Comment by lehne** [comment]
Do you know why I would be getting a 404 on /signin-mtsusi in my app?

**Comment by mrochon** [comment]
I have removed this policy from the latest version of my software so cannot even look for what could cause it in the older version, which I presume you are using. (mt_susi allowed users to join a tenant. I thought invitations are better but happy to be convinced otherwise). Ping me on sailingrock@ live.com - maybe we need to chat. Or, send me the url to your app.

**Comment by mrochon** [comment]
Hopefully stale.
