### ISSUE TITLE
best way to debug 404 when opening invite URL

### ISSUE THREAD

**Issue by DaehyunLee** [mrochon/b2csamples#12]
![image](https://user-images.githubusercontent.com/1912447/102706804-0e0f2080-4263-11eb-9eab-1fa822d8d13a.png)

I'm getting this when I follow the link to the invite. 
What would be the easiest way to find out what went wrong?

The URL looks like this
![image](https://user-images.githubusercontent.com/1912447/102706843-6514f580-4263-11eb-9b27-fd616a24da80.png)

Thank you very much for the sample.

**Comment by mrochon** [comment]
The [InvitationService creates the url](https://github.com/mrochon/b2c-mt-rest/blob/5c0f34535352342a7115f5a8958464ab30849f46/RESTFunctions/Services/InvitationService.cs#L38). Yours seems weird - you obscured the details but it seems much shorter than what the service creates before the .com suffix. It uses settings provided in the app config. Check the settings of the app service whether it has the correct tenant domain name.

**Comment by DaehyunLee** [comment]
Thank you @mrochon  for the info. 
After looking into the parameters, found out that the Uploaded policy names were set up differently.
