### ISSUE TITLE
Common-AAD or AAD-Common

### ISSUE THREAD

**Issue by reginbald** [mrochon/b2csamples#16]
https://github.com/mrochon/b2csamples/blob/c6fc362ccc4873b7aac460f3e84cf391ba142f1c/Policies/MultiTenant/InvitationExtensions.xml#L86

Is there a typo here?

**Comment by nomada2** [comment]
Is okay, run it

**Comment by mrochon** [comment]
No, not a typo. AAD-Common is pre-defined Technical Profile shared by all AAD-xyz Technical Profiles. These profiles deal with interactions with B2C data storage, e.g. persistence of user attributes. Common-AAD is the technical profile I have added to represent OIDC interaction with the corproate AAD /common (or /organizations) endpoint for logging in users who already have an Azure AD using the [AAD multi-tenancy support](https://docs.microsoft.com/en-us/azure/active-directory-b2c/identity-provider-azure-ad-multi-tenant?pivots=b2c-custom-policy). I should have used a better name perhaps. Sorry.
