### ISSUE TITLE
Question: Modifying an existing "default" Sign in v3 flow

### ISSUE THREAD

**Issue by las3r** [mrochon/b2csamples#17]
Hi there, and thanks for your repo with many examples, they are great!

I am looking to implement the AppRoles sample, but I want to use my current "user flow" (B2CSignIn_V3) as a base for this custom policy, since it already includes stuff like password change on expiration (in the flow), and MFA. All I want is the app roles customization in there, for the rest it is perfect. I know I need to use a custom flow, so this looks like the best bet.

I understand that I need the `REST-GetRoles` ClaimsProviders-part from the `TrustFrameworkExtensions.xml` file in your sample. 

How would I go about implementing this? Documentation is REALLY thin on this. Can I just add the `REST-GetRoles` part to my existing XML file and upload it as a custom policy? Or do I really need to "transcribe" the original user flow (xml) into the `TrustFrameworkBase`, `TrustFrameworkExtensions` and finally a nearly empty "policy"?

I understand how this all works technically, I just want to know whether its possible to drop this customization in the existing XML file. Thank you - I hope it makes sense.

**Comment by mrochon** [comment]
Sorry for not responding earlier. To use a REST function in a journey you need to use full IEF (Base, Extension, etc.) except for signup journeys if you want to validate attributes.
