### ISSUE TITLE
Fail to create a new Tenant after successful B2C Multi Tenant Deployment using script

### ISSUE THREAD

**Issue by vijayshiyani** [mrochon/b2csamples#19]
After successfully executing Setup-B2CMultiTenant.ps1 script @
https://github.com/mrochon/b2csamples/tree/master/Scripts/MultiTenant

Fail to create a new Tenant. 

it does hit b2c-mt-rest API but then throws 500 internal server error.

Are there any missing steps in the above deployment script? 
do we need to configure https://github.com/mrochon/b2c-mt-rest functions app separately? 

![image](https://user-images.githubusercontent.com/5908363/123910798-4a63cc00-d9be-11eb-97a2-77f6e057afcc.png)

**Comment by mrochon** [comment]
I suspect the REST API application registration in your B2C tenant has not been consented to. Look at its API Permissions and make sure admin consent has been granted.
