### ISSUE TITLE
Invite policy with client assertion deprecated?

### ISSUE THREAD

**Issue by davidspiess** [mrochon/b2csamples#28]
I noticed a warning in the B2C documentation that client assertion is deprecated.

![image](https://user-images.githubusercontent.com/992674/152299958-802a5d3c-edc4-4b66-941c-8353c02c1d03.png)

https://github.com/azure-ad-b2c/samples/blob/master/policies/invite_deprecated/Readme.md
Should the invite example be changed to accept an `id_token`?

**Comment by mrochon** [comment]
Custom policy using client_assertion is deprecated in lieu of the sample using id_token_hint. Use of client_assertion is not deprecated. However, AFAIK, it has never been properly documented either so yes, you are better off using id_token_hint going forward.
