### ISSUE TITLE
PromptForToAAD	Passes whatever prompt parameter was used with B2C to a federated AAD.

### ISSUE THREAD

**Issue by l-o-l** [mrochon/b2csamples#33]
Does not exist?

**Comment by mrochon** [comment]
Please clarify what you see and what you expected to see.

**Comment by l-o-l** [comment]
If you click the link from the landing page a 404 is returned. It’s there on the v2 branch and has solved all my problems. Which was very helpful! Thank you for making these examples!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
