### ISSUE TITLE
Unable to build Multitenant SPA

### ISSUE THREAD

**Issue by maurice-freitag** [mrochon/b2csamples#36]
Running `npm run build` for the React SPA in the multitenancy sample fails because the _public_ folder is missing, specifically _public\index.html_ is expected by `react-scripts`. The folder is specifically excluded in the .gitignore file which leads me to believe that this was done on purpose 🤔 I'm not sure what the plan here is. 

Workaround for anyone interested: Run `npx create-react-app my-app` which creates a new default react app, then copy the _public_ folder to _Policies\MultiTenant\source\UI_.

**Comment by mrochon** [comment]
Thanks for the comment. I am not that familiar with React so need some more explanation: should the _src_ folder have an empty _public_ folder for the npm run build to work? Would removing _public_ from .gitignore fix the issue?

**Comment by maurice-freitag** [comment]
There needs to be directory `MultiTenant\source\UI\public` (_next to_, not inside the src folder) with at least an `index.html` as this is expected by react-scripts. With that in place `npm run build` & `npm run start` should work again. My advice would be to add the [default index file](https://github.com/react-cosmos/create-react-app-example/blob/master/public/index.html), copy it into said folder and it from the .gitignore file.

**Comment by mrochon** [comment]
Thanks. Done. My .gitignore for some reason had *public* in it.
