### ISSUE TITLE
The -allowInit is obsolete with Connect-IEFPolicies

### ISSUE THREAD

**Issue by codepic** [mrochon/b2csamples#37]
The [readme](https://github.com/mrochon/b2csamples/blob/45d3fe201be8c7bf30801085172a4a5a38f48b6c/Policies/MultiTenant/Readme.md?plain=1#L44) on MultiTenant sample mentions `-allowInit` although it has been obsoleteted by [this commit](https://github.com/mrochon/IEFPolicies/commit/d4a931b087a09545f22c6a2ceaa9d80df06d16e8).

**Comment by mrochon** [comment]
Thanks. I checked in the change.
