### ISSUE TITLE
MultiTenant example. I can't invite a new user

### ISSUE THREAD

**Issue by DukaDima** [mrochon/b2csamples#49]
Hello. I am a beginner developer in Azure B2C. I found a link to this example on
https://stackoverflow.com/questions/54973828/azure-ad-b2c-multi-tenant
This script:
https://github.com/mrochon/b2csamples/tree/master/Policies/MultiTenant
perfect for my application. While trying to understand how the example works, I found that I couldn't invite the user. After creating the URL the answer is that the user does not exist. What's my mistake?
Is there a more detailed description of the code? Is it possible to implement the API on a Node JS?
![Знімок екрана 2022-09-23 о 14 38 00](https://user-images.githubusercontent.com/75967292/191953238-6236a36c-b9bc-45d5-8c79-94d7eb9b8005.png)
![Знімок екрана 2022-09-23 о 14 38 15](https://user-images.githubusercontent.com/75967292/191953285-9e4a49b9-a0f9-48b3-8561-0ef0d57a1467.png)

**Comment by mrochon** [comment]
Sorry, I did not realize you posted this issue. In case you are still needing the reply, the way this invitation works is that it just produces a url link that the invited user should use to redeem the invitation. Basically, copy the hyperlink called 'Invitation url' and enter it in a separate browser (you will get SSO in same browser). That will then take the user on the journey to prove their email address, set pwd, etc. Hope that help.
