### ISSUE TITLE
Documentation missing for user.IsInRole("ief")

### ISSUE THREAD

**Issue by HudsonJeff** [mrochon/b2csamples#65]
The MultiTenant rest api in Tenant.X509.cs references user.IsInRole("ief") as part of authorization.  No where in documentation for the sample is how this role is created or generated.  Knowing where and how this done would be helpful.

**Comment by mrochon** [comment]
It is done [in the certificate validation module](https://github.com/mrochon/b2csamples/blob/master/Policies/MultiTenant/source/API/RESTFunctions/Services/CertValidationMiddleware.cs#l36) to indicate that the call was made with a certificate rather than OAuth2 token.
