### ISSUE TITLE
Authorization of Users

### ISSUE THREAD

**Issue by amcorch** [mrochon/b2csamples#8]
Hi, I've been working through the samples you've provided for creating a multi-tenant B2C application and I was wondering if you have any thoughts on how to handle authorization within this scenario.

Is there a way that I could restrict access to certain endpoints within my application using this model. Preferably is there a way to assign permissions to a user or a group of users that would map to endpoints in my system?

**Comment by mrochon** [comment]
My multi-tenant sample uses groups to maintain user-to-tenant association. It then uses group owner/member dichotomy to give users admin or member role (authorization) with respect to that tenant. You could use [groups purely for [](roles](https://mrochon.azurewebsites.net/2019/05/06/using-groups-in-azure-ad-b2c/),) not tenants at all. Is that what you are looking for?

**Comment by mrochon** [comment]
No further action.
