### ISSUE TITLE
The forgot password option redirects to a localhost url

### ISSUE THREAD

**Issue by 4deeptech** [mrochon/b2csamples#9]
While playing around in the hosted demo app(https://b2cmultitenant.azurewebsites.net/) it redirects to: https://localhost:44369/signin-mtsusint when forgot password is clicked

**Comment by mrochon** [comment]
Thanks for letting me know. I am having trouble replicating the problem. Can you please give me repro steps? Did you use *Sign In* or *Create new tenant* when you got this error? Could you copy the url displayed in the browser address when you select the action?

**Comment by mrochon** [comment]
Sorry, did not finish reading before responding. Please ignore.

**Comment by mrochon** [comment]
Thanks! Fixed (the reply url used by the web site for pwd reset response was not registered as a valid reply url in B2C).
